[project]
name = "quiz_crm"
version = "0.0.1"
requires-python = ">=3.10"
description = "Quiz and Question management for CRM"
authors = [
    { name = "OurEdu", email = "dev@ouredu.com" }
]
dependencies = [
    "markdown>=3.7",
    "beautifulsoup4>=4.12",
    "requests>=2.31.0",
    "fuzzywuzzy>=0.18.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"