[project]
name = "quiz_crm"
dynamic = ["version"]
requires-python = ">=3.10"
description = "Quiz and Question management for CRM"
authors = [
    { name = "OurEdu", email = "dev@ouredu.com" }
]
dependencies = ["frappe"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core:buildapi"
